/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#000000",
        "outline-variant": "#c4c6cf",
        "on-primary-fixed-variant": "#31476b",
        "on-tertiary": "#ffffff",
        "surface": "#faf9fc",
        "on-secondary-fixed": "#00201a",
        "surface-container-high": "#e9e7eb",
        "on-error-container": "#93000a",
        "surface-bg": "#F8FAFC",
        "primary-container": "#001b3d",
        "surface-container-highest": "#e3e2e5",
        "surface-dim": "#dbd9dd",
        "success-glow": "#00F5D433",
        "tertiary-fixed-dim": "#fdb698",
        "on-background": "#1b1b1e",
        "inverse-on-surface": "#f2f0f3",
        "border-subtle": "#E2E8F0",
        "surface-tint": "#495f84",
        "on-error": "#ffffff",
        "primary-fixed": "#d6e3ff",
        "tertiary-container": "#351001",
        "tertiary-fixed": "#ffdbcd",
        "inverse-surface": "#303033",
        "secondary": "#006b5b",
        "surface-container-low": "#f5f3f6",
        "on-secondary-fixed-variant": "#005144",
        "secondary-fixed-dim": "#00dfc1",
        "secondary-fixed": "#26fedc",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#efedf1",
        "primary-fixed-dim": "#b1c7f2",
        "outline": "#74777f",
        "on-secondary-container": "#007261",
        "on-tertiary-fixed": "#351001",
        "inverse-primary": "#b1c7f2",
        "on-surface-variant": "#44474e",
        "on-primary-fixed": "#001b3d",
        "on-surface": "#1b1b1e",
        "on-tertiary-container": "#b2755b",
        "primary": "#000000",
        "secondary-container": "#26fedc",
        "on-primary": "#ffffff",
        "background": "#faf9fc",
        "on-tertiary-fixed-variant": "#6b3a24",
        "text-muted": "#64748B",
        "surface-bright": "#faf9fc",
        "on-primary-container": "#6f84ac",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "surface-variant": "#e3e2e5",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "unit": "8px",
        "margin-mobile": "16px",
        "bento-gap": "16px",
        "base": "8px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-xl": ["Plus Jakarta Sans", "sans-serif"],
        "mono-num": ["Inter", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["26px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "mono-num": ["16px", { lineHeight: "1", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
  ],
}
